### PR TITLE
Fix strings.xml files that were still typed as being symlinks

### PR DESCRIPTION
**Pull request by ElectricMagic**
*Issue #, if available:*
https://github.com/amzn/fire-app-builder/issues/73

*Description of changes:*
Some strings.xml files had been symlinks. Some had been
replaced with real files, but probably the work was done on a
Windows filesystem and the symlink flag in the git repo for the
files was not changed. So they became very long symlinks, which
can't be created on systems with shorter symlink length limits,
the Mac in my case, and thus checkout fails.

As symlinks seem to be causing trouble, I've fixed the
remaining values-en-rUS/strings.xml symlinks to be real
files with the content of what they were referencing.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Mariuxtheone** [comment]
@ElectricMagic just to clairfy: does your fork check out correctly on your machine?

**Comment by ElectricMagic** [comment]
Yes, it does:
```
hover:ag$ git clone --branch fix-strings-file-type git@github.com:ElectricMagic/fire-app-builder.git
Cloning into 'fire-app-builder'...
remote: Enumerating objects: 3307, done.
remote: Counting objects: 100% (217/217), done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 3307 (delta 79), reused 160 (delta 51), pack-reused 3090
Receiving objects: 100% (3307/3307), 10.49 MiB | 2.68 MiB/s, done.
Resolving deltas: 100% (987/987), done.
hover:ag$ 
```

**Comment by Mariuxtheone** [comment]
@ElectricMagic just a clarification. From our tests the _fix-strings-file-type_ branch checks out and compiles fine both on Mac and Windows, but not the master of your fork. We assume the master in your fork is untouched from FAB's current master as it returns the same errors. Can you confirm please?

**Comment by ElectricMagic** [comment]
@Mariuxtheone, yes I can confirm that -- the master in this repo is unchanged from the FAB master, the fix is in the `fix-strings-file-type` branch.

**Comment by Mariuxtheone** [comment]
Thanks @ElectricMagic for the support!

**Pull request merged**
